language: python
python:
    - 2.7
    - 2.6
install:
    - pip install pep8
    - pip install nose
    - pip install coverage
    - python setup.py install
before_script:
    # This is needed for Python multiprocessing.
    # https://github.com/travis-ci/travis-cookbooks/issues/155
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm 
script:
    - python setup.py nosetests
notifications:
    email:
        on_success: change
        on_failure: change
